openapi: '3.0.2'
info:
  title: API расчет стоимости доставки
  version: '1.0'
servers:
  - url: http://localhost:8080
paths:
  /delivery/calculate:
    get:
      parameters:
        - in: query
          name: name
          schema:
            type: number
            default: 1
          required: true
        - in: query
          name: email
          schema:
            type: string
            minimum: 3
            maximum: 12
            default: 'test@test.io'
          required: true
      responses:
        '200':
          description: OK
        '400':
          description: Validation error
